#! /bin/bash
shopt -s extglob

session=${1//@(.|\/)}

tmux has-session -t "$session" 2>/dev/null
if [ $? != 0 ]; then
    echo "Attaching to session $session"
    tmux attach -t "$session"
else
    echo "ERROR: Server $session not running"
    exit 1
fi